### ISSUE TITLE
gsd-analysis

### ISSUE THREAD

**Issue by tdunlap607** [cloudsecurityalliance/gsd-tools#107]
Hi All,

I'm sharing the repository ([gsd-analysis](https://github.com/tdunlap607/gsd-analysis)) I brought up Monday in the GSD meeting for analysis of the gsd-database. I made a few updates to the documentation for reproducibility. 

I think the README from the gsd-analysis repo starts to handle some of the "Data" to-dos for the GSD project, mainly for documentation purposes.

Example, the current overall data structure of the gsd-database:

```json
{
    "GSD": {"type":  "object"},
    "OSV": {"type":  "object"},
    "namespaces": {
        "properties": {
            "cisa.gov": {"type":  "object"},
            "cve.org": {"type":  "object"},
            "gitlab.com": {"type":  "object"},
            "nvd.nist.gov": {"type":  "object"},
            "github.com/kurtseifried:582211": {"type":  "object"}
        }
    },
    "overlay": {
        "properties": {
            "cve.org": {"type":  "object"}
        }
    }
}
```

GSD Object Schema: [./data/schemas/schema_gsd_object.json](https://github.com/tdunlap607/gsd-analysis/blob/main/data/schemas/schema_gsd_object.json)
OSV Schema: [./data/schemas/schema_osv.json](https://github.com/tdunlap607/gsd-analysis/blob/main/data/schemas/schema_osv.json)

Schemas would obviously need to be agreed/approved/validated before we could make any helper functions to validate incoming data into the gsd-database, but the gsd-analysis.py helps produce the initial bases for what's in the database. 

I'm currently unsure of the future home of the gsd-analysis; maybe a new tool within gsd-tools? Could it be the start of a dashboard? Also, while not the initial intention, it looks for inconsistencies/outliers within the gsd-database that could help with data cleansing. 

Let me know what you all think and the direction to potentially integrate the analysis into the project. 

Thanks!

**Comment by joshbuker** [comment]
This was merged into the tools repo, going to close it out until there's more on the topic.
