### ISSUE TITLE
Remove the old GSD namespace and put the OSV data in there

### ISSUE THREAD

**Issue by joshbressers** [cloudsecurityalliance/gsd-tools#142]
In our old data, we have a GSD and OSV namespace. The GSD namespace is old and not a standard. The OSV namespace in most instances will be a mirror of the GSD data. We should get rid of the old GSD space.

I would prefer we do not use a namespace called OSV as I think it's not clear that it has nothing to do with osv.dev

**Comment by kurtseifried** [comment]
Yup.

**Comment by joshbuker** [comment]
While the data still needs to be updated by the scripts @kurtseifried is currently working on, the schema has been updated to reflect this. Closing this out accordingly.
