### ISSUE TITLE
Document format of files

### ISSUE THREAD

**Issue by kurtseifried** [cloudsecurityalliance/gsd-tools#143]
Document format of files - waiting on email thread to confirm changes to file format. https://groups.google.com/a/groups.cloudsecurityalliance.org/g/gsd/c/DgSaS-lAsP4

**Comment by joshbuker** [comment]
@kurtseifried Lets ship this. There have been no objections, and this blocks working on the API and human interface.

**Comment by joshbuker** [comment]
This is done, see:
- https://raw.githubusercontent.com/cloudsecurityalliance/gsd-tools/schema-v1.0.0/gsd-schema/validation/schema.json
