### ISSUE TITLE
Link in https://github.com/cloudsecurityalliance/gsd-tools/blob/main/securitylist/README.md goes to 404

### ISSUE THREAD

**Issue by jasnow** [cloudsecurityalliance/gsd-tools#175]
[Link](https://github.com/distributedweaknessfiling/securitylist) iin https://github.com/cloudsecurityalliance/gsd-tools/blob/main/securitylist/README.md goes to 404

**Comment by joshbuker** [comment]
Good catch @jasnow, will fix shortly.
