### ISSUE TITLE
schema.gsd.id Cloudflare Worker for schema $refs

### ISSUE THREAD

**Issue by joshbuker** [cloudsecurityalliance/gsd-tools#177]
Allow validators to resolve even if the source returns text/plain

Transparent pull and reserve with proper content type.

**Comment by kurtseifried** [comment]
schema.gsd.id/DOMAIN/SCHEMA-NAME.json (latest) or SCHEMA-NAME-1.2.3.json correct?

so e.g. schema.gsd.id/osv.dev/osv-1.5.0.json or schema.gsd.id/gsd.id/osv-gsd-1.0.0.json





[16:42](https://cloudsecurityalliance.slack.com/archives/D1K1K3GKY/p1683672141397089)

**Comment by joshbuker** [comment]
I would be tempted to do a slightly different encoding, but that works, yes.

Alternative idea: https://schema.gsd.id/DOMAIN/SCHEMA-NAME/version

e.g.
https://schema.gsd.id/osv.dev/osv/latest
https://schema.gsd.id/osv.dev/osv/1.5.0
https://schema.gsd.id/gsd.id/osv-gsd/1.0.0

**Comment by kurtseifried** [comment]
I think your way is better. So I'll do that. Also for content type we'll use: application/schema+json as per the draft spec:

https://json-schema.org/draft/2019-09/json-schema-core.html

**Comment by kurtseifried** [comment]
Oh I remember why I wanted to do it my way, it can just be files in a directory attached to cloudflare pages.

**Comment by kurtseifried** [comment]
Ok as per discussion we went with human firendly and machine friendly layout:

For humans we have the files with the version number embedded, e.g.: gsd.id/osv-gsd/schema-osv-gsd-1.0.1.json

For computers we have the files in directories with the version number, e.g.: gsd.id/osv-gsd/1.0.1/schema.json

The latest version of the schema is in the root directory and called schema.json, e.g.: gsd.id/osv-gsd/schema.json

**Comment by kurtseifried** [comment]
also I'm using cloudflare pages which serves the json as "application/json" (and doesn't seem to lead _headers rewrite it), to get the proper "application/schema+json" we'll need to use a cloudflare worker or something that allows control of the header. That's a future problem/
