### ISSUE TITLE
Allow anyone to enrich existing vulnerabilities

### ISSUE THREAD

**Issue by joshbressers** [cloudsecurityalliance/gsd-tools#18]
Right now we have a web form to request one GSD ID
https://requests.globalsecuritydatabase.org/

This only allows one to request a new ID.

It is very common for a CVE ID to be lacking useful details. See this thread for an example
https://twitter.com/joshbressers/status/1492870755167748104

It would be valuable to have a way that isn't a PR to add such details to GSD.

I envision a workflow looking something like

- Load page for existing GSD
- Enrich data
- Submit data as issue
- Someone reviews the added data
- Add data to DB

We could skip the review step if we want to namespace the edits

**Comment by kurtseifried** [comment]
Can I also suggest as a related project we generate a list of CVE ID's missing data and for which public data from a reputable source exists, e.g. Debian/RedHat/AlpineLinux/various vendors. Posted to the GSD list for a bit of discussion:

https://groups.google.com/a/groups.cloudsecurityalliance.org/g/gsd/c/cKCtJI0O038

I think it might make sense to simply use the GSD entry to hold this, e.g. if we find a URL related to a CVE we at least add that URL to the GSD file, and the GSD files with alias CVE, and source URL(s) but no other data be presented in a way to make it easy for people to find and then enrich?

**Comment by joshbuker** [comment]
This is now supported via https://data.gsd.id (although it could always use some more polish...)
