### ISSUE TITLE
Update Edit Button to support all OSV fields

### ISSUE THREAD

**Issue by joshbuker** [cloudsecurityalliance/gsd-tools#192]
Currently supported:
- Summary
- Details
- References

Added by #196 
- published
- withdrawn
- aliases
- related
- severity
- credits
- affected

**Comment by joshbuker** [comment]
One note, might want to forcibly cast the datetime to the local timezone to prevent confusion when being used by drive-by contributors (will automatically save as UTC no matter what, but if a value exists it'll use UTC for the input as well).

**Comment by kurtseifried** [comment]
No, we should use UTC as per OSV/CVE:

https://ossf.github.io/osv-schema/#id-modified-fields

The published field gives the time the entry should be considered to have been published, as an RFC3339-formatted time stamp in UTC (ending in “Z”).

**Comment by joshbuker** [comment]
@kurtseifried To clarify, I'm talking about forcibly typecasting the _UI_, not the backend data. The data would always be read/saved as UTC, but we can display the time picker in the user's local time rather than force them to google "my timezone to UTC" every time (or have inaccurate data from drive-by contributors assuming it's in local time)
