### ISSUE TITLE
Only pulling in updates to GSD from CVE

### ISSUE THREAD

**Issue by raphaelahrens** [cloudsecurityalliance/gsd-tools#20]
https://github.com/cloudsecurityalliance/gsd-tools/blob/281714814ab1442108cee5c2577722fcf64369cd/securitylist/src/update_repo.py#L31

Since the CVE data is inside a git repo, it should be possible with something like this

```
pre_pull_commit=$(git rev-parse HEAD)
git pull
git diff --name-only "$pre_pull_commit" HEAD
```
It is possible to use [GitPython](https://github.com/gitpython-developers/GitPython) for this, but this is quite a large dependency and internally it uses the git executable.

For this the fetching of the CVEs should be moved from `securitylist/src/update.sh` into a separate fetch function.
It might in general be a good idea to have the fetching of the external sources (CVE, NVD, CISA, GitLab) in seperate modules and let these manage their own repos and caches.

**Comment by joshbuker** [comment]
@joshbressers It looks like you wrote the related code. Have you had a chance to look at this issue?

I'm not familiar enough with how we're importing the CVE data to really understand what's going on with the script without digging into the code for a bit.

**Comment by joshbuker** [comment]
Going to close this for now, but we can always reopen it if we want to revisit this improvement.
