### ISSUE TITLE
Update NVD automation to use the V2 api

### ISSUE THREAD

**Issue by westonsteimel** [cloudsecurityalliance/gsd-tools#224]
Update https://github.com/cloudsecurityalliance/gsd-tools/blob/main/securitylist/src/securitylist/NVD.py to use the [V2 NVD api](https://nvd.nist.gov/developers/vulnerabilities) as the V1 API will be retired in December: https://nvd.nist.gov/General/News/change-timeline

**Comment by oswalpalash** [comment]
Took a stab at this in the #230 PR. There's an overhaul in the way the API works now. Probably want @joshbressers to take a look at https://nvd.nist.gov/general/news/api-20-announcements the API change announcement to see if we should be doing more. I didn't have too much time to dabble with that.
