### ISSUE TITLE
Code of conduct [INSERT CONTACT METHOD]

### ISSUE THREAD

**Issue by raphaelahrens** [cloudsecurityalliance/gsd-tools#31]
Same as in https://github.com/cloudsecurityalliance/gsd-database/issues/2303

https://github.com/cloudsecurityalliance/gsd-tools/blob/3e9145d5d8b78acd46c8bfe25c75be5854b65a53/CODE_OF_CONDUCT.md?plain=1#L63

**Comment by kurtseifried** [comment]
Thanks, updated all 3. I hadn't set up inbound email, needed the reminder.
